Repository project-zot/zot, pull requests merged in 2022-08, with the labels that each got.

#694 fix dependabot alerts
  go.mod
  go.sum
Labels: dependencies

#711 fix dependabot alerts
  go.mod
  go.sum
Labels: dependencies

#695 replace dependency of tagsInfo with list of manifests
  pkg/extensions/search/common/oci_layout.go
  pkg/extensions/search/resolver.go
  pkg/extensions/search/resolver_test.go
  pkg/test/mocks/oci_mock.go
Labels: bug

#727 fix dependabot alerts
  go.mod
  go.sum
Labels: dependencies

#638 support OCI image index at manifest endpoint
  .github/workflows/ecosystem-tools.yaml
  pkg/api/controller_test.go
  pkg/storage/local.go
  pkg/storage/s3/s3.go
  pkg/storage/s3/s3_test.go
  test/blackbox/pushpull.bats
Labels: enhancement

#457 [cloud usecase] zot cli should not download manifests when listing images
  golangcilint.yaml
  pkg/cli/client.go
  pkg/cli/client_test.go
  pkg/cli/cve_cmd.go
  pkg/cli/cve_cmd_test.go
  pkg/cli/image_cmd.go
  pkg/cli/image_cmd_test.go
  pkg/cli/searcher.go
  pkg/cli/service.go
  pkg/extensions/search/common/common.go
  pkg/extensions/search/common/common_test.go
  pkg/extensions/search/common/oci_layout.go
  pkg/extensions/search/cve/cve.go
  pkg/extensions/search/cve/cve_test.go
  pkg/extensions/search/cve/models.go
  pkg/extensions/search/digest/digest.go
  pkg/extensions/search/digest/digest_test.go
  pkg/extensions/search/gql_generated/generated.go
  pkg/extensions/search/gql_generated/models_gen.go
  pkg/extensions/search/resolver.go
  pkg/extensions/search/resolver_test.go
  pkg/extensions/search/schema.graphql
  pkg/extensions/search/schema.resolvers.go
Labels: cli

#742 fix artifact upload action in github workflow
  .github/workflows/ci-cd.yml
Labels: ci/cd

#728 graphql: Apply authorization on /_search endpoint
  examples/config-tls.json
  pkg/api/authz.go
  pkg/api/controller_test.go
  pkg/api/routes.go
  pkg/extensions/extension_search.go
  pkg/extensions/search/common/common_test.go
  pkg/extensions/search/resolver.go
  pkg/extensions/search/resolver_test.go
  pkg/extensions/search/schema.resolvers.go
  pkg/requestcontext/context.go
  pkg/test/common.go
  pkg/test/common_test.go
  pkg/test/dev.go
  pkg/test/inject_test.go
  pkg/test/prod.go
Labels: enhancement

#764 Updates following the new oras version
  .github/workflows/cluster.yaml
  .github/workflows/codeql-analysis.yml
  Makefile
  demos/oras-push-pull.svg
  pkg/extensions/sync/sync_test.go
  test/blackbox/pushpull.bats
Labels: ci/cd, dependencies

#718 storage: different subpaths can point to same root directory
  pkg/api/config/config.go
  pkg/api/config/config_elevated_test.go
  pkg/api/config/config_test.go
  pkg/api/controller.go
  pkg/api/controller_test.go
  pkg/cli/root.go
  pkg/cli/root_test.go
  pkg/extensions/sync/sync_test.go
Labels: enhancement
