Repository project-zot/zot, pull requests merged in 2022-10, with the labels that each got.

#848 fix(license-check): also account for another result condition
  Makefile
Labels: ci/cd

#753 feat(GraphQL): playground, served by zot in specific binary
  examples/config-search.json
  pkg/api/routes.go
  pkg/debug/constants/consts.go
  pkg/debug/gqlplayground/gqlplayground.go
  pkg/debug/gqlplayground/gqlplayground_disabled.go
  pkg/debug/gqlplayground/index.html.tmpl
  pkg/extensions/search/gql_generated/generated.go
  pkg/extensions/search/gql_generated/models_gen.go
  pkg/extensions/search/schema.graphql
Labels: feature

#810 ci(workflows): changed workflow to generate introspection json when gql schema changed
  .github/workflows/ci-cd.yml
  pkg/debug/githubWorkflows/introspection-query.json
Labels: documentation, ci/cd

#854 build: add commit hash to Config at build for proper discovery readme
  .github/workflows/ci-cd.yml
  Makefile
  pkg/api/config/config.go
  pkg/extensions/extension_search.go
  stacker.yaml
Labels: documentation
