Repository project-zot/zot, pull requests merged in 2022-02, with the labels that each got.

#393 search: graphql api to give detailed repo info
  go.mod
  pkg/extensions/search/common/common_test.go
  pkg/extensions/search/common/oci_layout.go
  pkg/extensions/search/generated.go
  pkg/extensions/search/models_gen.go
  pkg/extensions/search/resolver.go
  pkg/extensions/search/schema.graphql
Labels: enhancement

#408 dependabot-alert: update 'github.com/open-policy-agent/opa'
  go.mod
  go.sum
Labels: bug

#388 update README.md
  README.md
  examples/config-minimal.json
Labels: documentation

#414 ci/cd: add a workflow to detect/close stale PRs and issues
  .github/workflows/stale.yaml
Labels: enhancement, ci/cd, awaiting-feedback
