Repository project-zot/zot, pull requests merged in 2022-11, with the labels that each got.

#936 feat(artifact): add OCI references support
  Makefile
  README.md
  go.mod
  go.sum
  pkg/api/controller_test.go
  pkg/api/routes.go
  pkg/debug/gqlplayground/gqlplayground_disabled.go
  pkg/debug/swagger/swagger_disabled.go
  pkg/extensions/extension_sync.go
  pkg/extensions/extension_sync_disabled.go
  pkg/extensions/search/common/common_test.go
  pkg/extensions/search/common/oci_layout.go
  pkg/extensions/search/resolver_test.go
  pkg/extensions/sync/on_demand.go
  pkg/extensions/sync/signatures.go
  pkg/extensions/sync/sync_test.go
  pkg/storage/common.go
  pkg/storage/constants/constants.go
  pkg/storage/local/local.go
  pkg/storage/local/local_test.go
  pkg/storage/s3/s3.go
  pkg/storage/s3/s3_test.go
  pkg/storage/storage.go
  pkg/test/common.go
  pkg/test/mocks/image_store_mock.go
  test/blackbox/pushpull.bats
Labels: feature

#986 build: move build artifacts into build/
  .github/workflows/ci-cd.yml
  Makefile
  README.md
  build/Dockerfile
  build/Dockerfile-conformance
  build/Dockerfile-minimal
  build/Dockerfile-zb
  build/Dockerfile-zxp
  build/stacker-conformance.yaml
  build/stacker-zb.yaml
  build/stacker-zxp.yaml
  build/stacker.yaml
  examples/metrics/Makefile
  test/blackbox/annotations.bats
Labels: bug

#990 fix(ci): fix releasing zot minimal image
  build/stacker-conformance.yaml
  build/stacker-zb.yaml
  build/stacker-zxp.yaml
  build/stacker.yaml
Labels: bug

#991 fix(ci): set correct arch/os for published container images
  build/stacker-conformance.yaml
  build/stacker-zb.yaml
  build/stacker-zxp.yaml
  build/stacker.yaml
Labels: bug

#1001 doc: update README with minimal image and urls
  README.md
Labels: documentation

#985 feat(sync,s3): added s3 logic for ORAS and OCI artifacts
  errors/errors.go
  pkg/api/routes.go
  pkg/extensions/extension_sync.go
  pkg/extensions/extension_sync_disabled.go
  pkg/extensions/sync/on_demand.go
  pkg/extensions/sync/signatures.go
  pkg/extensions/sync/sync.go
  pkg/extensions/sync/sync_internal_test.go
  pkg/extensions/sync/sync_test.go
  pkg/extensions/sync/utils.go
  pkg/storage/common.go
  pkg/storage/common_test.go
  pkg/storage/local/local.go
  pkg/storage/s3/s3.go
  pkg/storage/s3/s3_test.go
Labels: feature

#951 fix(storage): deleting manifests with identical digests
  Makefile
  errors/errors.go
  examples/README.md
  examples/config-policy.json
  pkg/api/authz.go
  pkg/api/controller_test.go
  pkg/api/routes.go
  pkg/api/routes_test.go
  pkg/extensions/search/resolver.go
  pkg/extensions/search/resolver_test.go
  pkg/extensions/sync/sync_test.go
  pkg/requestcontext/context.go
  pkg/storage/common.go
  pkg/storage/local/local.go
  pkg/storage/local/local_test.go
  pkg/storage/s3/s3.go
  pkg/storage/s3/s3_test.go
  pkg/storage/storage.go
  pkg/storage/storage_test.go
  pkg/test/mocks/image_store_mock.go
  test/blackbox/anonymous_policy.bats
  test/blackbox/detect_manifest_collision.bats
Labels: feature

#953 feat(cache): dynamodb implementation
  .github/workflows/ci-cd.yml
  .github/workflows/ecosystem-tools.yaml
  Makefile
  examples/config-dynamodb.json
  examples/config-s3.json
  go.mod
  go.sum
  pkg/api/config/config.go
  pkg/api/controller.go
  pkg/api/controller_test.go
  pkg/cli/root.go
  pkg/cli/root_test.go
  pkg/extensions/sync/on_demand.go
  pkg/storage/cache.go
  pkg/storage/cache/boltdb.go
  pkg/storage/cache/dynamodb.go
  pkg/storage/cache/dynamodb_test.go
  pkg/storage/cache_benchmark_test.go
  pkg/storage/constants/constants.go
  pkg/storage/s3/s3_test.go
  test/blackbox/cloud-only.bats
  test/blackbox/helpers_cloud.bash
Labels: feature

#1009 feat(graphql): add an api to return referrers
  pkg/extensions/search/common/common_test.go
  pkg/extensions/search/common/model.go
  pkg/extensions/search/gql_generated/generated.go
  pkg/extensions/search/gql_generated/models_gen.go
  pkg/extensions/search/resolver.go
  pkg/extensions/search/resolver_test.go
  pkg/extensions/search/schema.graphql
  pkg/extensions/search/schema.resolvers.go
  pkg/test/common.go
  pkg/test/common_test.go
Labels: feature, ui

#1030 chore(deps): fix dependabot alerts
  go.mod
  go.sum
Labels: dependencies

#1033 perf(zb): cleanup tool output
  README.md
  cmd/zb/README.md
  cmd/zb/perf.go
Labels: performance
