Repository project-zot/zot, pull requests merged in 2022-04, with the labels that each got.

#440 make scrub inline and periodic
  examples/config-allextensions.json
  examples/config-scrub.json
  pkg/api/controller.go
  pkg/cli/extensions_test.go
  pkg/cli/root.go
  pkg/extensions/config/config.go
  pkg/extensions/extensions.go
  pkg/extensions/minimal.go
  pkg/extensions/scrub/scrub.go
  pkg/extensions/scrub/scrub_test.go
  pkg/storage/scrub.go
Labels: enhancement

#491 demos: initial commit of asciinema demos
  .github/workflows/golangci-lint.yaml
  README.md
  demos/README.md
  demos/cosign.json
  demos/cosign.svg
  demos/dev-getting-started.rec
  demos/dev-getting-started.svg
  demos/docker-getting-started.rec
  demos/docker-getting-started.svg
  demos/multi-arch-getting-started.rec
  demos/multi-arch-getting-started.svg
  demos/notation.json
  demos/notation.svg
  demos/oras-push-pull.json
  demos/oras-push-pull.svg
  demos/podman-getting-started.rec
  demos/podman-getting-started.svg
  demos/skopeo-push-pull.json
  demos/skopeo-push-pull.svg
Labels: documentation

#496 update 3rd party licenses
  THIRD-PARTY-LICENSES.md
Labels: documentation

#469 s3: fix initRepo not creating index.json in some edge cases
  pkg/storage/s3/s3_test.go
  pkg/storage/s3/storage.go
Labels: bug

#513 build(deps): bump github.com/swaggo/http-swagger from 1.2.5 to 1.2.6
  go.mod
  go.sum
Labels: bug, security

#514 codeql: move from v1 to v2
  .github/workflows/ci-cd.yml
  .github/workflows/codeql-analysis.yml
Labels: ci/cd
