Repository project-zot/zot, pull requests merged in 2022-05, with the labels that each got.

#445 storage: prevent tag overwrites controlled via configuration
  examples/config-default-authz.json
  pkg/api/authz.go
  pkg/api/config/config.go
  pkg/api/controller_test.go
  pkg/api/routes.go
  pkg/cli/root.go
  pkg/cli/root_test.go
Labels: enhancement

#518 dependabot alert: fix CVE-2022-29810
  go.mod
  go.sum
  golangcilint.yaml
Labels: bug, security

#520 add a CODEOWNERS file
  CODEOWNERS
Labels: documentation

#517 use TempDir instead of /tmp/zot in tests
  pkg/cli/extensions_test.go
Labels: bug

#523 zb: fix usage help output
  cmd/zb/main.go
Labels: documentation, performance

#493 Reduce downloads by grouping .sync dirs for all images in the same repo
  pkg/extensions/sync/on_demand.go
  pkg/extensions/sync/sync.go
  pkg/extensions/sync/sync_internal_test.go
  pkg/extensions/sync/sync_test.go
  pkg/extensions/sync/utils.go
Labels: enhancement

#521 Report unknown keys when parsing configuration files
  pkg/api/config/config.go
  pkg/api/controller.go
  pkg/cli/root.go
  pkg/cli/root_test.go
Labels: enhancement

#500 Adding mocked tests for routes
  pkg/api/routes.go
  pkg/api/routes_test.go
Labels: ci/cd

#544 update cosign deps
  go.mod
  go.sum
Labels: dependencies

#449 ext: use distribution spec route prefix for extension api
  .github/workflows/ci-cd.yml
  Makefile
  cmd/zb/perf.go
  examples/config-allextensions.json
  examples/config-bearer-auth.json
  examples/config-bench.json
  examples/config-commit.json
  examples/config-conformance.json
  examples/config-cve.json
  examples/config-default-authz.json
  examples/config-example.json
  examples/config-example.yaml
  examples/config-gc-periodic.json
  examples/config-gc.json
  examples/config-metrics.json
  examples/config-minimal.json
  examples/config-multiple-cve.json
  examples/config-multiple.json
  examples/config-policy.json
  examples/config-ratelimit.json
  examples/config-s3.json
  examples/config-scrub.json
  examples/config-sync.json
  examples/config-test.json
  examples/config-tls.json
  go.mod
  go.sum
  pkg/api/authz.go
  pkg/api/constants/consts.go
  pkg/api/constants/extensions.go
  pkg/api/controller_test.go
  pkg/api/routes.go
  pkg/cli/client_elevated_test.go
  pkg/cli/client_test.go
  pkg/cli/config_cmd_test.go
  pkg/cli/cve_cmd_test.go
  pkg/cli/root.go
  pkg/cli/service.go
  pkg/compliance/v1_0_0/check.go
  pkg/extensions/_search.md
  pkg/extensions/extensions.go
  pkg/extensions/minimal.go
  pkg/extensions/search/common/common_test.go
  pkg/extensions/search/cve/cve_test.go
  pkg/extensions/search/digest/digest_test.go
  pkg/extensions/sync/sync.go
  pkg/extensions/sync/sync_test.go
  swagger/docs.go
  swagger/swagger.json
  swagger/swagger.yaml
Labels: enhancement, conformance

#545 fix stacker build file to include compatible glibc runtime
  stacker-conformance.yaml
  stacker-zb.yaml
  stacker-zxp.yaml
  stacker.yaml
Labels: bug

#550 fix CVE-2022-29162/GHSA-f3fp-gc8g-vw66
  go.mod
  go.sum
  golangcilint.yaml
Labels: bug, security

#504 s3: added logic for deduping blobs
  examples/README.md
  examples/config-s3.json
  pkg/api/controller.go
  pkg/api/controller_test.go
  pkg/storage/cache.go
  pkg/storage/cache_test.go
  pkg/storage/s3/s3_test.go
  pkg/storage/s3/storage.go
  pkg/storage/storage_fs.go
  pkg/storage/storage_test.go
  test/cluster/config-minio.json
Labels: enhancement

#552 fix CVE-2022-29173/GHSA-66x3-6cw3-v5gj
  go.mod
  go.sum
  golangcilint.yaml
  pkg/api/controller_test.go
  pkg/extensions/sync/sync_test.go
Labels: bug, security
