Repository project-zot/zot, pull requests merged in 2022-03, with the labels that each got.

#437 remove linger go.sum entries to fix dependabot alert
  go.sum
Labels: bug, security

#436 s3: bugfix, use sync.Map instead of map for storing multi part upload…
  pkg/storage/s3/storage.go
  pkg/storage/storage_fs.go
Labels: bug

#439 CVE-2022-23648: update dependencies in go.mod
  go.mod
  go.sum
Labels: bug, security

#443 conformance: fix cross-mount behavior when 'from' is missing
  pkg/api/controller_test.go
  pkg/api/routes.go
Labels: bug, conformance

#429 routes: changes required to do browser authentication
  pkg/api/authn.go
  pkg/api/config/config.go
  pkg/api/controller.go
  pkg/api/controller_test.go
  pkg/api/routes.go
  pkg/extensions/extensions.go
  pkg/extensions/search/cve/cve_test.go
Labels: enhancement

#460 fix dependabot alert
  examples/config-allextensions.json
  examples/config-bearer-auth.json
  examples/config-commit.json
  examples/config-conformance.json
  examples/config-cve.json
  examples/config-example.json
  examples/config-gc.json
  examples/config-metrics.json
  examples/config-minimal.json
  examples/config-multiple-cve.json
  examples/config-multiple.json
  examples/config-policy.json
  examples/config-ratelimit.json
  examples/config-s3.json
  examples/config-sync.json
  examples/config-test.json
  examples/config-tls.json
  go.mod
  go.sum
Labels: bug, security

#453 ci/cd: scan released images with trivy scanner
  .github/workflows/ci-cd.yml
Labels: enhancement, ci/cd, security

#473 move module deps under project-zot repo
  go.mod
  go.sum
Labels: dependencies

#381 Leave zot repositories in a consistent state after zot hits fd limit closes #359
  .github/workflows/ci-cd.yml
  Makefile
  pkg/api/controller_test.go
  pkg/api/errors.go
  pkg/api/routes.go
  pkg/cli/stress_test.go
  pkg/storage/storage_fs.go
Labels: bug
