Repository project-zot/zot, pull requests merged in 2022-07, with the labels that each got.

#605 Add a way to list imports used by specific binaries
  Makefile
Labels: enhancement

#620 Fix test data races
  pkg/cli/extensions_test.go
  pkg/test/common.go
Labels: bug

#643 harden github action/workflow perms
  .github/workflows/ci-cd.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/ecosystem-tools.yaml
  .github/workflows/oci-conformance-action.yml
  .github/workflows/stale.yaml
  .github/workflows/sync-golang-image.yaml
Labels: ci/cd, security

#637 GetRefferers of any artifactType, not just application/vnd.cncf.notary.v2.signature
  pkg/storage/local.go
  pkg/storage/local_test.go
Labels: bug

#655 add a github workflow to report branch coverage
  .github/workflows/branch-cov.yml
Labels: ci/cd

#671 RepoSummary has a new attribute NewestTag of type ImageSummary
  pkg/extensions/search/common/common_test.go
  pkg/extensions/search/common/oci_layout.go
  pkg/extensions/search/gql_generated/generated.go
  pkg/extensions/search/gql_generated/models_gen.go
  pkg/extensions/search/resolver.go
  pkg/extensions/search/resolver_test.go
  pkg/extensions/search/schema.graphql
  pkg/test/mocks/oci_mock.go
Labels: ui

#601 Fuzzing for local storage
  Makefile
  README_fuzz.md
  pkg/storage/local.go
  pkg/storage/local_test.go
  pkg/storage/storage_test.go
  test/scripts/fuzzAll.sh
Labels: enhancement, ci/cd
