Repository project-zot/zot, pull requests merged in 2022-09, with the labels that each got.

#754 Skip manifest which have no annotation for tags
  pkg/extensions/search/common/common_test.go
  pkg/extensions/search/common/oci_layout.go
Labels: enhancement

#770 report listening port when chosen by kernel
  errors/errors.go
  pkg/api/controller.go
  pkg/api/controller_test.go
  pkg/cli/root.go
  pkg/cli/root_test.go
Labels: feature

#765 routes: support resumable pull
  errors/errors.go
  pkg/api/controller_test.go
  pkg/api/routes.go
  pkg/storage/cache.go
  pkg/storage/local.go
  pkg/storage/local_test.go
  pkg/storage/s3/s3.go
  pkg/storage/s3/s3_test.go
  pkg/storage/storage.go
  pkg/test/mocks/image_store_mock.go
Labels: good first issue, conformance

#791 update README.md for release
  README.md
Labels: documentation

#784 update ImageSummary to return the history of an image
  pkg/extensions/search/common/common_test.go
  pkg/extensions/search/gql_generated/generated.go
  pkg/extensions/search/gql_generated/models_gen.go
  pkg/extensions/search/resolver.go
  pkg/extensions/search/schema.graphql
  pkg/extensions/search/schema.resolvers.go
Labels: feature
